owner: vaibhav0806
repo: vala-backend-status

sites:
  - name: Vala Backend Health
    url: https://backend.vala.media/api/v1/health
    expectedStatusCodes:
      - 404
    maxResponseTime: 5000
    
  # - name: Vala Backend Liveness
  #   url: https://backend.vala.media/health/liveness
  #   expectedStatusCodes:
  #     - 200
      
  # - name: Vala Backend Readiness
  #   url: https://backend.vala.media/health/readiness
  #   expectedStatusCodes:
  #     - 200

status-website:
  baseUrl: /vala-backend-status
  name: Vala Backend Status 
  logoUrl: https://cdn.prod.website-files.com/66d3a0873f16fc3af8dd7d3c/679a24fa2c532b406d361f2c_VALA.svg
  introTitle: "**Vala** Backend Status"
  introMessage: Real-time monitoring of Vala backend services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark  # or 'light'

# Upptime configuration
workflowSchedule:
  uptime: "*/5 * * * *"  # Check every 5 minutes
  responseTime: "0 23 * * *"  # Update graphs daily
  graphs: "0 0 * * *"  # Generate graphs daily
  
assignees:
  - vaibhav0806

user-agent: upptime
